# Generated by Django 5.2.8 on 2025-11-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id_equipos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('numero_serie_equipo', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'equipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instalaciones',
            fields=[
                ('id_instalaciones', models.AutoField(primary_key=True, serialize=False)),
                ('numero_serie_equipo', models.CharField(max_length=100, unique=True)),
                ('numero_de_orden', models.CharField(max_length=100)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('id_tecnico_empresa', models.CharField(max_length=50)),
                ('nombre_tecnico', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_orden', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'instalaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id_operador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_operador', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'operador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_orden', models.CharField(max_length=100)),
                ('puntos_orden', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_orden_tecnico', models.TextField(blank=True, null=True)),
                ('valor_orden_empresa', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ordenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tecnicos',
            fields=[
                ('id_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tecnico', models.CharField(max_length=150)),
                ('id_tecnico_empresa', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tecnicos',
                'managed': False,
            },
        ),
    ]
